### ISSUE TITLE
Projects API

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/api.ce.pdn.ac.lk#3]
Design APIs to obtain the details in the [projects.ce.pdn.ac.lk](projects.ce.pdn.ac.lk) 

### API Endpoints
- [x] List Project Categories
- [x] List Projects by Category
- [x] List Projects by Batch
- [x] List Project by Category + Batch
- [x] Get details of the project by RepoName
- [x] List Projects by Student 
- [ ] ~~List Projects by Supervisor~~
- [x] Tag the projects based on the topics

### TODOs
- [x] Write python script
- [x] Swagger API definitions
- [x] Documentation Page
- [x] Add GitHub action

### Information available on 
- https://projects.ce.pdn.ac.lk/api/categories/
- https://projects.ce.pdn.ac.lk/api/all/
- GitHub API for obtain the topics: https://api.github.com/repos/cepdnaclk/{repo_name}/topics
