### ISSUE TITLE
Publication API

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/api.ce.pdn.ac.lk#5]
The main purpose of this API is to manage a single repository on the department's research publications.

- The API will be used by the ESCAL web 
- Can integrate with the other websites/pages in the department such as Computer Vision, Cyber Security, etc...
- Can add the publication details to the Staff and People profile pages 

### TODO
- [x] Identify the parameters need to collect
- [x] Identify the way we can collect the publication information 
- [x] Design the data repository (Git Repo / Google Sheet / Google Form)
   - [x] Google Form 
- [x] Design the procedures for long term sustainability 
- [x] Implement the APIs 
- [x] Write the API documentation

**Comment by NuwanJ** [comment]
Discussion Summary (2021-12-19):
- Identify the required fields for the publications
- Add "affiliation" as a parameter, and only show the papers with CE Affiliation in the frontend web 
- Will add a Mentor from E15 to guide the development team about the publications 
- Prepare a Google Form to collect publication data
- Design a data structure to keep them 
- Will appoint a maintainer(s) to collect the publication data and update in the repo based on the **Form** responses

**Comment by NuwanJ** [comment]
It was decided to implement the Publication information collection from a well-designed Google Form at this time and directly process the details in api.ce.pdn.ac.lk. Later will be moving this into a separate repository

**Comment by NuwanJ** [comment]
Commit [765908d](https://github.com/cepdnaclk/api.ce.pdn.ac.lk/commit/765908d9422fc4cb37a8ac68c51a2f29622c79e8) implemented the basic setup + workflow (daily updates)

Information can be provided from the Google Form, https://forms.gle/vAPghP9c96a19bNY9

**Comment by NuwanJ** [comment]
There is a suggestion to have a public Discord Channel and update every new publication information there. ( automated by the Google Actions )

The advantage is everyone can see it and get an idea about the latest publications in the department (as a News) 
In addition to that, we can use it to moderate the content.

- @gihanjayatilaka

**Comment by NuwanJ** [comment]
Publication API documentation is now available from https://api.ce.pdn.ac.lk/docs/publications/#/
