### ISSUE TITLE
Discord Channel for publication updates  

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/api.ce.pdn.ac.lk#9]
This is related to #5 

### Objectives
- Update students about the publication updates 
- Encourage to submit the publications (long term sustainability)
- Crowdsourced Content moderation (to avoid adding harmful/fake content - since anyone with eng email can type anything and submit)

### TODO
- [ ] Discuss about this with Discord Moderator Team 
- [x] Update the projects.py to Trigger a Discord webhook when a new file is created 
- [ ] Create Discord Chat + Webhook 
- [ ] Documentate the functionality for future use / updates

**Comment by gihanjayatilaka** [comment]
@NuwanJ Are we going to use api.ce.pdn.ac.lk discord channel for updates?

**Comment by NuwanJ** [comment]
Just for testings

**Comment by gihanjayatilaka** [comment]
Okay :-)
